//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvnCommiter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Config : global::System.Configuration.ApplicationSettingsBase {
        
        private static Config defaultInstance = ((Config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Config())));
        		  	 			 	
        public static Config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xsj.kingsoft.net/DevSimple/Task/SvnCommiterDirect.aspx")]
        public string CommitUrl {
            get {
                return ((string)(this["CommitUrl"]));
            }
            set {
                this["CommitUrl"] = value;			   	 	 	
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]				  			 	
        [global::System.Configuration.DefaultSettingValueAttribute("svn_bin/svn.exe")]
        public string SvnPath {
            get {
                return ((string)(this["SvnPath"]));
            }
            set {
                this["SvnPath"] = value;
            }
        }
        			 	 			 	
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FoldPaths {
            get {
                return ((string)(this["FoldPaths"]));
            }
            set {
                this["FoldPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("svn_bin/svn6.exe")]
        public string Svn6Path {
            get {
                return ((string)(this["Svn6Path"]));
            }
            set {
                this["Svn6Path"] = value;			  				 	
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("svn_bin/svn7.exe")]			 	 			 	
        public string Svn7Path {
            get {
                return ((string)(this["Svn7Path"]));
            }
            set {
                this["Svn7Path"] = value;									 	
            }
        }
    }
}
									 	